-dontwarn com.google.**
-dontwarn io.grpc.**
-dontwarn okio.**
-keep class com.google.android.libraries.navigation.** { *; }
-keep class com.google.android.libraries.mapsplatform.transportation.** { *; }
